-- MySQL Script generated by MySQL Workbench
-- Wed Mar 22 13:50:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema immo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema immo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `immo` DEFAULT CHARACTER SET utf8 ;
USE `immo` ;

-- -----------------------------------------------------
-- Table `immo`.`Property`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immo`.`Property` (
  `idProperty` INT NOT NULL AUTO_INCREMENT,
  `adresse` VARCHAR(45) NULL,
  `code_postal` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NULL,
  `etat` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `intitule` VARCHAR(45) NULL,
  `prix` INT NULL,
  `superficie` INT NULL,
  `pieces` INT NULL,
  `chambres` INT NULL,
  `meuble` TINYINT NULL,
  `piscine` TINYINT NULL,
  `balcon` TINYINT NULL,
  `jardin` TINYINT NULL,
  `garage` TINYINT NULL,
  `cave` TINYINT NULL,
  `ascenseur` TINYINT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`idProperty`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immo`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immo`.`Admin` (
  `idAdmin` INT NOT NULL,
  `identifiant` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `Property_idProperty` INT NOT NULL,
  PRIMARY KEY (`idAdmin`),
  INDEX `fk_Admin_Property1_idx` (`Property_idProperty` ASC),
  CONSTRAINT `fk_Admin_Property1`
    FOREIGN KEY (`Property_idProperty`)
    REFERENCES `immo`.`Property` (`idProperty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immo`.`photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immo`.`photos` (
  `idphotos` INT NOT NULL,
  `photo` VARCHAR(45) NULL,
  `Property_idProperty` INT NOT NULL,
  PRIMARY KEY (`idphotos`),
  INDEX `fk_photos_Property1_idx` (`Property_idProperty` ASC),
  CONSTRAINT `fk_photos_Property1`
    FOREIGN KEY (`Property_idProperty`)
    REFERENCES `immo`.`Property` (`idProperty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
