-- MySQL Script generated by MySQL Workbench
-- Wed Mar 22 13:50:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema immo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema immo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `immo` DEFAULT CHARACTER SET utf8 ;
USE `immo` ;

-- -----------------------------------------------------
-- Table `immo`.`Property`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immo`.`Property` (
  `idProperty` INT NOT NULL AUTO_INCREMENT,
  `adresse` VARCHAR(45) NULL,
  `code_postal` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NULL,
  `etat` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `intitule` VARCHAR(100) NULL,
  `prix` INT NULL,
  `superficie` INT NULL,
  `pieces` INT NULL,
  `chambres` INT NULL,
  `meuble` TINYINT NULL,
  `piscine` TINYINT NULL,
  `balcon` TINYINT NULL,
  `jardin` TINYINT NULL,
  `garage` TINYINT NULL,
  `cave` TINYINT NULL,
  `ascenseur` TINYINT NULL,
  `description` TEXT NULL,
  `etage` TINYINT NULL,
  PRIMARY KEY (`idProperty`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immo`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immo`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `identifiant` VARCHAR(45) NULL,
  `password` VARCHAR(100) NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `immo`.`photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immo`.`photos` (
  `idphotos` INT NOT NULL AUTO_INCREMENT,
  `photo` VARCHAR(45) NULL,
  `Property_idProperty` INT NOT NULL,
  PRIMARY KEY (`idphotos`),
  INDEX `fk_photos_Property1_idx` (`Property_idProperty` ASC),
  CONSTRAINT `fk_photos_Property1`
    FOREIGN KEY (`Property_idProperty`)
    REFERENCES `immo`.`Property` (`idProperty`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO Admin (identifiant, password) VALUES ('admin', '$2y$10$Fscf7ylMSOecMCyXefVck.1WCRbIj9/zMOkoYjno0NYAPF.gMrLCe')

INSERT INTO Property (adresse, code_postal, ville, etat, type, intitule, prix, superficie, pieces, chambres, meuble, piscine, balcon, jardin, garage, cave, ascenseur, etage, description) VALUES
('5 rue de la paix', '38000', 'Grenoble', 'Location', 'Appartement', 'Joli appart', 760, 62, 3, 2, 0, 0, 1, 0, 1, 1, 1, 7, "Appartement proche de toutes commodité (transport, écoles, commerces), se situant à 2 pas du centre historique de Grenoble. Le quartier est calme et résidentiel et bénéficie d'une atmosphère familiale. L'appratement est agréable et lumineux et est idéal pour un jeune couple ou une collocation étudiante."),
('560 chemin des grenadier', '13600', 'La Ciotat', 'Achat', 'Maison', 'Belle maison près de la mer', 790000, 182, 6, 5, 1, 1, 0, 1, 0, 1, 1, 2, "Belle maison spacieuse à 150m de la plage de La Ciotat. La maison bénéficie d'un grand jardin, et d'une piscine de 1080 litres. La cuisine et le salon se trouve au rez-de-chaussée. Quant aux chambres et à la salle de bain sont à l'étage. Le bien comprend aussi une cave et un garage au rdc. Parfaitement situé à La Ciotat, la maison est idéal pour une famille nombreuse.");


INSERT INTO Property (adresse, code_postal, ville, etat, type, intitule, prix, superficie, pieces, chambres, meuble, piscine, balcon, jardin, garage, cave, ascenseur, etage, description) VALUES
('5 rue de la paix', '38000', 'Grenoble', 'Location', 'Appartement', 'Joli appart', 760, 62, 3, 2, 0, 0, 1, 0, 1, 1, 1, 7, "Appartement proche de toutes commodité (transport, écoles, commerces), se situant à 2 pas du centre historique de Grenoble. Le quartier est calme et résidentiel et bénéficie d'une atmosphère familiale. L'appratement est agréable et lumineux et est idéal pour un jeune couple ou une collocation étudiante."),
('560 chemin des grenadier', '13600', 'La Ciotat', 'Achat', 'Maison', 'Belle maison près de la mer', 790000, 182, 6, 5, 1, 1, 0, 1, 0, 1, 1, 2, "Belle maison spacieuse à 150m de la plage de La Ciotat. La maison bénéficie d'un grand jardin, et d'une piscine de 1080 litres. La cuisine et le salon se trouve au rez-de-chaussée. Quant aux chambres et à la salle de bain sont à l'étage. Le bien comprend aussi une cave et un garage au rdc. Parfaitement situé à La Ciotat, la maison est idéal pour une famille nombreuse."),
('5 rue de la paix', '38000', 'Grenoble', 'Location', 'Appartement', 'Joli appart', 760, 62, 3, 2, 0, 0, 1, 0, 1, 1, 1, 7, "Appartement proche de toutes commodité (transport, écoles, commerces), se situant à 2 pas du centre historique de Grenoble. Le quartier est calme et résidentiel et bénéficie d'une atmosphère familiale. L'appratement est agréable et lumineux et est idéal pour un jeune couple ou une collocation étudiante."),
('560 chemin des grenadier', '13600', 'La Ciotat', 'Achat', 'Maison', 'Belle maison près de la mer', 790000, 182, 6, 5, 1, 1, 0, 1, 0, 1, 1, 2, "Belle maison spacieuse à 150m de la plage de La Ciotat. La maison bénéficie d'un grand jardin, et d'une piscine de 1080 litres. La cuisine et le salon se trouve au rez-de-chaussée. Quant aux chambres et à la salle de bain sont à l'étage. Le bien comprend aussi une cave et un garage au rdc. Parfaitement situé à La Ciotat, la maison est idéal pour une famille nombreuse."),
('5 rue de la paix', '38000', 'Grenoble', 'Location', 'Appartement', 'Joli appart', 760, 62, 3, 2, 0, 0, 1, 0, 1, 1, 1, 7, "Appartement proche de toutes commodité (transport, écoles, commerces), se situant à 2 pas du centre historique de Grenoble. Le quartier est calme et résidentiel et bénéficie d'une atmosphère familiale. L'appratement est agréable et lumineux et est idéal pour un jeune couple ou une collocation étudiante."),
('560 chemin des grenadier', '13600', 'La Ciotat', 'Achat', 'Maison', 'Belle maison près de la mer', 790000, 182, 6, 5, 1, 1, 0, 1, 0, 1, 1, 2, "Belle maison spacieuse à 150m de la plage de La Ciotat. La maison bénéficie d'un grand jardin, et d'une piscine de 1080 litres. La cuisine et le salon se trouve au rez-de-chaussée. Quant aux chambres et à la salle de bain sont à l'étage. Le bien comprend aussi une cave et un garage au rdc. Parfaitement situé à La Ciotat, la maison est idéal pour une famille nombreuse."),
('5 rue de la paix', '38000', 'Grenoble', 'Location', 'Appartement', 'Joli appart', 760, 62, 3, 2, 0, 0, 1, 0, 1, 1, 1, 7, "Appartement proche de toutes commodité (transport, écoles, commerces), se situant à 2 pas du centre historique de Grenoble. Le quartier est calme et résidentiel et bénéficie d'une atmosphère familiale. L'appratement est agréable et lumineux et est idéal pour un jeune couple ou une collocation étudiante."),
('560 chemin des grenadier', '13600', 'La Ciotat', 'Achat', 'Maison', 'Belle maison près de la mer', 790000, 182, 6, 5, 1, 1, 0, 1, 0, 1, 1, 2, "Belle maison spacieuse à 150m de la plage de La Ciotat. La maison bénéficie d'un grand jardin, et d'une piscine de 1080 litres. La cuisine et le salon se trouve au rez-de-chaussée. Quant aux chambres et à la salle de bain sont à l'étage. Le bien comprend aussi une cave et un garage au rdc. Parfaitement situé à La Ciotat, la maison est idéal pour une famille nombreuse."),
('5 rue de la paix', '38000', 'Grenoble', 'Location', 'Appartement', 'Joli appart', 760, 62, 3, 2, 0, 0, 1, 0, 1, 1, 1, 7, "Appartement proche de toutes commodité (transport, écoles, commerces), se situant à 2 pas du centre historique de Grenoble. Le quartier est calme et résidentiel et bénéficie d'une atmosphère familiale. L'appratement est agréable et lumineux et est idéal pour un jeune couple ou une collocation étudiante."),
('560 chemin des grenadier', '13600', 'La Ciotat', 'Achat', 'Maison', 'Belle maison près de la mer', 790000, 182, 6, 5, 1, 1, 0, 1, 0, 1, 1, 2, "Belle maison spacieuse à 150m de la plage de La Ciotat. La maison bénéficie d'un grand jardin, et d'une piscine de 1080 litres. La cuisine et le salon se trouve au rez-de-chaussée. Quant aux chambres et à la salle de bain sont à l'étage. Le bien comprend aussi une cave et un garage au rdc. Parfaitement situé à La Ciotat, la maison est idéal pour une famille nombreuse."),
('5 rue de la paix', '38000', 'Grenoble', 'Location', 'Appartement', 'Joli appart', 760, 62, 3, 2, 0, 0, 1, 0, 1, 1, 1, 7, "Appartement proche de toutes commodité (transport, écoles, commerces), se situant à 2 pas du centre historique de Grenoble. Le quartier est calme et résidentiel et bénéficie d'une atmosphère familiale. L'appratement est agréable et lumineux et est idéal pour un jeune couple ou une collocation étudiante."),
('560 chemin des grenadier', '13600', 'La Ciotat', 'Achat', 'Maison', 'Belle maison près de la mer', 790000, 182, 6, 5, 1, 1, 0, 1, 0, 1, 1, 2, "Belle maison spacieuse à 150m de la plage de La Ciotat. La maison bénéficie d'un grand jardin, et d'une piscine de 1080 litres. La cuisine et le salon se trouve au rez-de-chaussée. Quant aux chambres et à la salle de bain sont à l'étage. Le bien comprend aussi une cave et un garage au rdc. Parfaitement situé à La Ciotat, la maison est idéal pour une famille nombreuse."),
('5 rue de la paix', '38000', 'Grenoble', 'Location', 'Appartement', 'Joli appart', 760, 62, 3, 2, 0, 0, 1, 0, 1, 1, 1, 7, "Appartement proche de toutes commodité (transport, écoles, commerces), se situant à 2 pas du centre historique de Grenoble. Le quartier est calme et résidentiel et bénéficie d'une atmosphère familiale. L'appratement est agréable et lumineux et est idéal pour un jeune couple ou une collocation étudiante."),
('560 chemin des grenadier', '13600', 'La Ciotat', 'Achat', 'Maison', 'Belle maison près de la mer', 790000, 182, 6, 5, 1, 1, 0, 1, 0, 1, 1, 2, "Belle maison spacieuse à 150m de la plage de La Ciotat. La maison bénéficie d'un grand jardin, et d'une piscine de 1080 litres. La cuisine et le salon se trouve au rez-de-chaussée. Quant aux chambres et à la salle de bain sont à l'étage. Le bien comprend aussi une cave et un garage au rdc. Parfaitement situé à La Ciotat, la maison est idéal pour une famille nombreuse."),
('5 rue de la paix', '38000', 'Grenoble', 'Location', 'Appartement', 'Joli appart', 760, 62, 3, 2, 0, 0, 1, 0, 1, 1, 1, 7, "Appartement proche de toutes commodité (transport, écoles, commerces), se situant à 2 pas du centre historique de Grenoble. Le quartier est calme et résidentiel et bénéficie d'une atmosphère familiale. L'appratement est agréable et lumineux et est idéal pour un jeune couple ou une collocation étudiante."),
('560 chemin des grenadier', '13600', 'La Ciotat', 'Achat', 'Maison', 'Belle maison près de la mer', 790000, 182, 6, 5, 1, 1, 0, 1, 0, 1, 1, 2, "Belle maison spacieuse à 150m de la plage de La Ciotat. La maison bénéficie d'un grand jardin, et d'une piscine de 1080 litres. La cuisine et le salon se trouve au rez-de-chaussée. Quant aux chambres et à la salle de bain sont à l'étage. Le bien comprend aussi une cave et un garage au rdc. Parfaitement situé à La Ciotat, la maison est idéal pour une famille nombreuse."),
('5 rue de la paix', '38000', 'Grenoble', 'Location', 'Appartement', 'Joli appart', 760, 62, 3, 2, 0, 0, 1, 0, 1, 1, 1, 7, "Appartement proche de toutes commodité (transport, écoles, commerces), se situant à 2 pas du centre historique de Grenoble. Le quartier est calme et résidentiel et bénéficie d'une atmosphère familiale. L'appratement est agréable et lumineux et est idéal pour un jeune couple ou une collocation étudiante."),
('560 chemin des grenadier', '13600', 'La Ciotat', 'Achat', 'Maison', 'Belle maison près de la mer', 790000, 182, 6, 5, 1, 1, 0, 1, 0, 1, 1, 2, "Belle maison spacieuse à 150m de la plage de La Ciotat. La maison bénéficie d'un grand jardin, et d'une piscine de 1080 litres. La cuisine et le salon se trouve au rez-de-chaussée. Quant aux chambres et à la salle de bain sont à l'étage. Le bien comprend aussi une cave et un garage au rdc. Parfaitement situé à La Ciotat, la maison est idéal pour une famille nombreuse."),
('5 rue de la paix', '38000', 'Grenoble', 'Location', 'Appartement', 'Joli appart', 760, 62, 3, 2, 0, 0, 1, 0, 1, 1, 1, 7, "Appartement proche de toutes commodité (transport, écoles, commerces), se situant à 2 pas du centre historique de Grenoble. Le quartier est calme et résidentiel et bénéficie d'une atmosphère familiale. L'appratement est agréable et lumineux et est idéal pour un jeune couple ou une collocation étudiante."),
('560 chemin des grenadier', '13600', 'La Ciotat', 'Achat', 'Maison', 'Belle maison près de la mer', 790000, 182, 6, 5, 1, 1, 0, 1, 0, 1, 1, 2, "Belle maison spacieuse à 150m de la plage de La Ciotat. La maison bénéficie d'un grand jardin, et d'une piscine de 1080 litres. La cuisine et le salon se trouve au rez-de-chaussée. Quant aux chambres et à la salle de bain sont à l'étage. Le bien comprend aussi une cave et un garage au rdc. Parfaitement situé à La Ciotat, la maison est idéal pour une famille nombreuse.");

